import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import axios from "axios";
import { useDispatch, useSelector } from "react-redux";
import { CharacterCard } from "../components/CharacterCard";
import {
  addFavoriteCharacter,
  addMovies,
  setFeaturedMovie,
} from "../store/reducer/moviesReducer";
import styles from "../styles/Home.module.css";
import { Layout } from "../Layout";
import client from "../apollo-client";
import { gql } from "@apollo/client";

const Home: NextPage<{ characters: any[] }> = ({ characters }) => {
  const dispatch = useDispatch();

  const handleAddFavoriteCharacter = (movie: any) => {
    dispatch(addFavoriteCharacter(movie));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty with GraphQL by Yosef Blandin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section
          className={styles.cardsContainer}
          data-testid="Home_cardsContainer"
        >
          {characters.map((character: any) => (
            <CharacterCard
              handleClick={() => handleAddFavoriteCharacter(character)}
              key={character.id}
              id={character.id}
              img={character.image}
              name={character.name}
              contentType={character.species}
            />
          ))}
        </section>
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  const { data } = await client.query({
    query: gql`
      query ExampleQuery {
        characters {
          results {
            id
            name
            species
            image
          }
        }
      }
    `,
  });
  return {
    props: {
      characters: data.characters.results,
    },
  };
}

export default Home;
