import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import axios from "axios";
import { useDispatch, useSelector } from "react-redux";
import { CharacterCard } from "../components/CharacterCard";
import {
  addFavoriteCharacter,
  addMovies,
  setFeaturedMovie,
} from "../store/reducer/moviesReducer";
import styles from "../styles/Home.module.css";
import { Layout } from "../Layout";

const Home: NextPage = () => {
  const movies = useSelector((state: any) => state.movies.movies);
  const favoriteCharacters = useSelector(
    (state: any) => state.movies.favoriteCharacters
  );
  const dispatch = useDispatch();
  let fetchedCharacters: any = {};
  const fetchData = async () => {
    fetchedCharacters = await axios.get("/api/fetchCharacters");
    console.log(fetchedCharacters);
    dispatch(addMovies(fetchedCharacters.data.results));
  };

  const handleAddFavoriteCharacter = (movie: any) => {
    dispatch(addFavoriteCharacter(movie));
  };

  useEffect(() => {
    fetchData();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick and Morty by Yosef Blandin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.cardsContainer}>
          {movies.map((character: any) => (
            <CharacterCard
              handleClick={() => handleAddFavoriteCharacter(character)}
              key={character.id}
              id={character.id}
              img={character.image}
              name={character.name}
              contentType={character.species}
            />
          ))}
        </section>
      </main>
    </div>
  );
};

export default Home;
